
public enum Purpose {
	CURRENT,
	ADMIN,
	DEVELOP,
	TAILORING,
	PSEUDO_ANALYSIS,
	PSEUDO_DECISION,
	INDIVIDUAL_ANALYSIS,
	INDIVIDUAL_DECISION,
	CONTACT,
	HISTORICAL,
	TELEMARKETING,
	OTHER_PURPOSE,
	CUSTOMIZATION;
}